In [1]:
from pyspoc import Calculator, Config

Starting JVM with java class /Users/joshparchure/Documents/pyspocClone24Jun/py-spoc/pyspoc/lib/jidt/infodynamics.jar.
Jpype JVM not available: [Errno 2] JVM DLL not found: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

In [2]:
from pathlib import Path
import os
import numpy as np
import pandas as pd
project_root = Path('./').resolve().parents[2]

Here we will run some ReducedStatistics on some synthetic datasets which were generated according to some random linear SCM on the "chain" and "loop" structured DAGs.

---
# Running reduced statistics
## 1) Distance Distribution Stats
### a) Euclidean distances; mean centroid; estimating number of peaks with KDE

In [3]:
distance_distrib_stats_path = os.path.join(project_root,'hjResearch_2025','summary_stats','distance_distrib_stats.py')
print(distance_distrib_stats_path)

/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py

In [4]:
kde_config_yaml = f"""
ReducedStatistics:
  {distance_distrib_stats_path}:
    DistanceDistributionModesSummarize:
      schemes:
        scheme_1:
          metric: euclidean
          point: global_mean_centroid
          type: kde
"""
kde_config_name = "kde_euclidean_globalmeancentroid"
cfg = Config.from_yaml(kde_config_name, kde_config_yaml)

Registering YAML string.
Building internal configuration.
/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py
    ✔ ReducedStatistic DistanceDistributionModesSummarize scheme 'scheme_1' added successfully.

In [5]:
def process_motivation_dag(dag_number, project_root):

    base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'motivationAnalysis')
    meta_file = os.path.join(base_dir, f'motivation_dag_{dag_number}.csv')
    
    print(f"--- Processing motivation_dag_{dag_number}.csv ---")
    meta_df = pd.read_csv(meta_file)
    display(meta_df)

    calc = Calculator(meta_df)
    calc.compute(cfg)
    results = calc.results
    print(results)

process_motivation_dag(1, project_root)
process_motivation_dag(2, project_root)

--- Processing motivation_dag_1.csv ---

           V0        V1        V2
0   -1.309975 -0.210383 -0.561118
1   -0.286121 -1.210426 -1.000506
2   -0.338890 -0.660613 -0.724111
3   -0.372171 -0.032225 -0.151854
4   -0.166640 -0.283169 -0.177887
..        ...       ...       ...
995  1.542328  0.405907  0.674028
996  0.502690  1.449731  1.260039
997  0.300818  1.296965  1.185995
998 -0.332102 -1.175522 -0.875340
999  0.998632  0.685157  0.859886

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 109.73it/s]

Calculation complete. Time taken: 0.0096s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1
Reducer                                                                                                                                                               self
0                                                        2.0
--- Processing motivation_dag_2.csv ---

           V0        V1        V2
0   -0.232403 -0.391251 -0.270432
1    0.276521  0.266542  0.311923
2   -0.160806 -0.093603  0.021258
3   -0.174242 -0.221482 -0.329510
4   -0.186991 -0.097720 -0.329971
..        ...       ...       ...
995 -1.863905 -1.773036 -1.395144
996 -1.611131 -1.434023 -1.679805
997 -1.720087 -1.215960 -1.793412
998 -1.320740 -1.161177 -1.474408
999 -1.606012 -1.598749 -1.791309

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 177.49it/s]

Calculation complete. Time taken: 0.0060s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionModesSummarize.scheme_1
Reducer                                                                                                                                                               self
0                                                        2.0

### b) Euclidean distances; mean centroid; mean

In [6]:
euclideanMetric_meanCentroid_config_yaml = f"""
ReducedStatistics:
  {distance_distrib_stats_path}:
    DistanceDistributionBasicSummarize:
      schemes:
        scheme_1:
          metric: euclidean
          stats: 
            - mean
            - median
            - iqr
            - std
            - min
            - max
          point: global_mean_centroid
"""
euclideanMetric_meanCentroid_config_name = "kde_euclidean_globalmeancentroid"
cfg = Config.from_yaml(euclideanMetric_meanCentroid_config_name, euclideanMetric_meanCentroid_config_yaml )

Registering YAML string.
Building internal configuration.
  ✔ Module /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py already loaded.
    ✔ ReducedStatistic DistanceDistributionBasicSummarize scheme 'scheme_1' added successfully.

In [7]:
process_motivation_dag(1, project_root)
process_motivation_dag(2, project_root)

--- Processing motivation_dag_1.csv ---

           V0        V1        V2
0   -1.309975 -0.210383 -0.561118
1   -0.286121 -1.210426 -1.000506
2   -0.338890 -0.660613 -0.724111
3   -0.372171 -0.032225 -0.151854
4   -0.166640 -0.283169 -0.177887
..        ...       ...       ...
995  1.542328  0.405907  0.674028
996  0.502690  1.449731  1.260039
997  0.300818  1.296965  1.185995
998 -0.332102 -1.175522 -0.875340
999  0.998632  0.685157  0.859886

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionBasicSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 1232.89it/s]

Calculation complete. Time taken: 0.0011s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionBasicSummarize.scheme_1  \
Reducer                                                                                                                                                             self_1
0                                                   1.449594

Statistic
Reducer      self_2    self_3    self_4    self_5    self_6
0          1.322242  1.135401  0.838542  0.079522  5.006403
--- Processing motivation_dag_2.csv ---

           V0        V1        V2
0   -0.232403 -0.391251 -0.270432
1    0.276521  0.266542  0.311923
2   -0.160806 -0.093603  0.021258
3   -0.174242 -0.221482 -0.329510
4   -0.186991 -0.097720 -0.329971
..        ...       ...       ...
995 -1.863905 -1.773036 -1.395144
996 -1.611131 -1.434023 -1.679805
997 -1.720087 -1.215960 -1.793412
998 -1.320740 -1.161177 -1.474408
999 -1.606012 -1.598749 -1.791309

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionBasicSummarize.scheme_1]:   0%|          | 0/1 [00:00<?, ?it/s]

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionBasicSummarize.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 49.06it/s]

Calculation complete. Time taken: 0.0213s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/distance_distrib_stats.py.DistanceDistributionBasicSummarize.scheme_1  \
Reducer                                                                                                                                                             self_1
0                                                   1.394103

Statistic
Reducer     self_2    self_3    self_4    self_5    self_6
0          0.99809  1.761552  1.025736  0.042018  4.364321

---
## 2) Feature Covariance Stats
### Empiricial covariance matrix: 
- largest non diagonal covariance entry per feature; median/max/min
- ratio of AM and GM of eigenvalues: isotropy/how spherical the data is
- von neumann entropy: isotropy, mixing??

In [12]:
feature_covariance_stats_path = os.path.join(project_root,'hjResearch_2025','summary_stats','feature_covariance_stats.py')
print(feature_covariance_stats_path)

/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py

In [13]:
covariance_config_yaml = f"""
Statistics:
    pyspoc.statistics.basic:
        Covariance:
            schemes:
                empirical:
                    estimator: EmpiricalCovariance
Reducers:
  {feature_covariance_stats_path}:
    MaxCovPerFeature:
        schemes:
          max_min_median:
            stats: 
              - max
              - min
              - median
    EigenAMGMRatio:
      schemes:
        eigen_amgm:        
    EigenEntropy:
      schemes:
        eigen_entropy:
"""
covariance_config_name = "covariance"
cfg = Config.from_yaml(covariance_config_name, covariance_config_yaml)

Registering YAML string.
Building internal configuration.
  ✔ Module pyspoc.statistics.basic already loaded.
    ✔ Statistic Covariance scheme 'empirical' added successfully.
  ✔ Module /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py already loaded.
    ✔ Reducer MaxCovPerFeature scheme 'max_min_median' added successfully.
    ✔ Reducer EigenAMGMRatio scheme 'eigen_amgm' added successfully.
    ✔ Reducer EigenEntropy scheme 'eigen_entropy' added successfully.

In [ ]:
# base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'dataGen','chain100data')
# meta_file = os.path.join(base_dir, f'dag1dataset1.csv')

# meta_df = pd.read_csv(meta_file)
# display(meta_df)

# calc = Calculator(meta_df)
# calc.compute(cfg)
# results = calc.results
# print(results)

# # base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'dataGen','loop100data')
# # meta_file = os.path.join(base_dir, f'dag2dataset1.csv')

# covariance_config_name = "covariance"
# cfg = Config.from_yaml(covariance_config_name, covariance_config_yaml)

# base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'motivationAnalysis')
# meta_file = os.path.join(base_dir, f'motivation_dag_1.csv')

# meta_df = pd.read_csv(meta_file)
# display(meta_df)

# calc = Calculator(meta_df)
# calc.compute(cfg)
# results = calc.results
# print(results)

In [19]:
process_motivation_dag(1, project_root)
covariance_config_name = "covariance"
cfg = Config.from_yaml(covariance_config_name, covariance_config_yaml)
process_motivation_dag(2, project_root)

--- Processing motivation_dag_1.csv ---

           V0        V1        V2
0   -1.309975 -0.210383 -0.561118
1   -0.286121 -1.210426 -1.000506
2   -0.338890 -0.660613 -0.724111
3   -0.372171 -0.032225 -0.151854
4   -0.166640 -0.283169 -0.177887
..        ...       ...       ...
995  1.542328  0.405907  0.674028
996  0.502690  1.449731  1.260039
997  0.300818  1.296965  1.185995
998 -0.332102 -1.175522 -0.875340
999  0.998632  0.685157  0.859886

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: pyspoc.statistics.basic.Covariance.empirical]: 100%|██████████| 1/1 [00:00<00:00, 1017.29it/s]
Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenEntropy.eigen_entropy]: 100%|██████████| 3/3 [00:00<00:00, 1302.71it/s]

Calculation complete. Time taken: 0.0038s
Statistic                                                                                                             pyspoc.statistics.basic.Covariance.empirical  \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_1
0                                                   0.961337

Statistic                                                                                                                                                           \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_2
0                                                   0.181031

Statistic                                                                                                                                                           \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_3
0                                                   0.961337

Statistic                                                                                                                                                   \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenAMGMRatio.eigen_amgm
0                                                   3.557673

Statistic
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenEntropy.eigen_entropy
0                                                   0.623462
Registering YAML string.
Building internal configuration.
  ✔ Module pyspoc.statistics.basic already loaded.
    ✔ Statistic Covariance scheme 'empirical' added successfully.
  ✔ Module /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py already loaded.
    ✔ Reducer MaxCovPerFeature scheme 'max_min_median' added successfully.
    ✔ Reducer EigenAMGMRatio scheme 'eigen_amgm' added successfully.
    ✔ Reducer EigenEntropy scheme 'eigen_entropy' added successfully.
--- Processing motivation_dag_2.csv ---

           V0        V1        V2
0   -0.232403 -0.391251 -0.270432
1    0.276521  0.266542  0.311923
2   -0.160806 -0.093603  0.021258
3   -0.174242 -0.221482 -0.329510
4   -0.186991 -0.097720 -0.329971
..        ...       ...       ...
995 -1.863905 -1.773036 -1.395144
996 -1.611131 -1.434023 -1.679805
997 -1.720087 -1.215960 -1.793412
998 -1.320740 -1.161177 -1.474408
999 -1.606012 -1.598749 -1.791309

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: pyspoc.statistics.basic.Covariance.empirical]: 100%|██████████| 1/1 [00:00<00:00, 694.42it/s]
Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenEntropy.eigen_entropy]: 100%|██████████| 3/3 [00:00<00:00, 1905.92it/s]

Calculation complete. Time taken: 0.0037s
Statistic                                                                                                             pyspoc.statistics.basic.Covariance.empirical  \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_1
0                                                   0.971939

Statistic                                                                                                                                                           \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_2
0                                                   0.952241

Statistic                                                                                                                                                           \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.MaxCovPerFeature.max_min_median_3
0                                                   0.971939

Statistic                                                                                                                                                   \
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenAMGMRatio.eigen_amgm
0                                                   6.037954

Statistic
Reducer   /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/feature_covariance_stats.py.EigenEntropy.eigen_entropy
0                                                   0.148328

---
## 3) Mean median differences - skewness

In [22]:
mean_median_diff_stats_path = os.path.join(project_root,'hjResearch_2025','summary_stats','mean_median_differences.py')
print(mean_median_diff_stats_path)

/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py

In [ ]:
mean_median_diff_config_yaml = f"""
ReducedStatistics:
  {mean_median_diff_stats_path}:
    GlobalMeanMedianDiff:
      schemes:
        scheme_1:
"""
mean_median_diff_config_name = "skewness_mean_median_diff"
cfg = Config.from_yaml(mean_median_diff_config_name, mean_median_diff_config_yaml)

Registering YAML string.
Building internal configuration.
/Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py
    ✔ ReducedStatistic GlobalMeanMedianDiff scheme 'scheme_1' added successfully.

In [24]:
process_motivation_dag(1, project_root)
process_motivation_dag(2, project_root)

--- Processing motivation_dag_1.csv ---

           V0        V1        V2
0   -1.309975 -0.210383 -0.561118
1   -0.286121 -1.210426 -1.000506
2   -0.338890 -0.660613 -0.724111
3   -0.372171 -0.032225 -0.151854
4   -0.166640 -0.283169 -0.177887
..        ...       ...       ...
995  1.542328  0.405907  0.674028
996  0.502690  1.449731  1.260039
997  0.300818  1.296965  1.185995
998 -0.332102 -1.175522 -0.875340
999  0.998632  0.685157  0.859886

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py.GlobalMeanMedianDiff.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 1282.27it/s]

Calculation complete. Time taken: 0.0010s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py.GlobalMeanMedianDiff.scheme_1
Reducer                                                                                                                                                  self
0                                                   0.083157
--- Processing motivation_dag_2.csv ---

           V0        V1        V2
0   -0.232403 -0.391251 -0.270432
1    0.276521  0.266542  0.311923
2   -0.160806 -0.093603  0.021258
3   -0.174242 -0.221482 -0.329510
4   -0.186991 -0.097720 -0.329971
..        ...       ...       ...
995 -1.863905 -1.773036 -1.395144
996 -1.611131 -1.434023 -1.679805
997 -1.720087 -1.215960 -1.793412
998 -1.320740 -1.161177 -1.474408
999 -1.606012 -1.598749 -1.791309

[1000 rows x 3 columns]

Normalising the dataset...

Processing [None: /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py.GlobalMeanMedianDiff.scheme_1]: 100%|██████████| 1/1 [00:00<00:00, 1412.22it/s]

Calculation complete. Time taken: 0.0010s
Statistic /Users/joshparchure/pyspocClone5Aug/py-spoc/working_analyses/hjResearch_2025/summary_stats/mean_median_differences.py.GlobalMeanMedianDiff.scheme_1
Reducer                                                                                                                                                  self
0                                                    0.13188